@extends('layouts.app')

@section('content')
    @component('particals.jumbotron')
        <div class="jumbotron jumbotron-fluid"></div>
        <h3 class="text-center" style="margin-top: 5%">
            Законодавство,що здійснює регулювання роботи ДНЗ
        </h3>
        <div class='post-header'>
            <div class='post-header-line-1'></div>
        </div>
        <div class='post-body entry-content'  itemprop='description articleBody' style="margin-top:2%">
            <div dir="ltr" style="text-align: left;" trbidi="on">

                <div>
                    <div class="hover"  onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4  class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family:georgia , times new roman , serif">
                            <span style="font-family:courier new ,courier; , monospace;"><span style="font-family: georgia , times new roman , serif;">І.</span><span style="font-family: georgia , times new roman , serif;">
                                    Базові </span></span><span style="font-family: georgia , times new roman , serif; font-style: inherit;">документи</span>
                        </span>
                    </h4>
                    <div style="border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul style="background-color: rgba(255, 255, 255, 0.309804); margin-left:10%;">
                            <li><span style="font-family:georgia , times new roman , serif"><span style="line-height: 20.8px;">Закон України &#171;Про освіту&#187; (Відомості Верховної Ради України (ВВР), 2017, N 38-39, ст.380). <a href="http://zakon3.rada.gov.ua/laws/show/2145-19" target="_blank">Джерело</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Закон України &#171;Про дошкільну освіту&#187; (Відомості Верховної Ради України (ВВР), 2001, N 49, ст.259) {Із змінами, внесеними згідно із Законами від 16.10.2012}</span><span style="color: blue;"><span style="line-height: 20.8px;">&nbsp;</span><span style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/01.doc" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Базовий компонент дошкільної освіти (нова редакція).&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/02.doc" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Закон України &#171;Про фізичну культуру і спорт&#187; від 24 грудня 1993 р. &#8470;3808-ХІІ, зі змінами від 18 червня 1999 р.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/03.doc" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Закон України &#171;Про охорону дитинства&#187; від 26 квітня 2001 р. &#8470;2402-ІІІ, зі змінами від 24 квітня 2008 р.</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon1.rada.gov.ua/laws/show/2402-14" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Закон України &#171;Про Державний Гімн України&#187; від 6 березня 2003 р. &#8470;602-ІV.</span><span style="color: blue;"><span style="line-height: 20.8px;">&nbsp;</span><span style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon1.rada.gov.ua/laws/show/602-iv" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Конвенція про права дитини.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/06.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Концепція Державної цільової програми розвитку дошкільної освіти на період до 2017 року (&#8470;1721-р від 27.08.2010).</span><span style="color: #363636; line-height: 20.8px;"> </span><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/07.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Конституція України.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/254%D0%BA/96-%D0%B2%D1%80" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про затвердження Нормативів наповнюваності груп дошкільних навчальних закладів (ясел-садків)компенсуючого типу, класів спеціальних-загально-освітніх шкіл (шкіл-інтернатів), груп подовженого дня і виховних груп загальноосвітніх навчальних закладів усіх типів та порядку поділу класів на групи при вивчені окремих предметів загальноосвітніх навчальних закладах (наказ МОН України &#8470;128 від 20.02.2002).&nbsp;</span><span style="color: blue;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/09.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">П</a><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/09.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">ереглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок створення, реорганізації та ліквідації навчально-виховних закладів, затверджений постановою Кабінету Міністерства України від 05.04.1994.</span><span style="color: blue;"><span style="line-height: 20.8px;">&nbsp;</span><span style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon1.rada.gov.ua/laws/show/228-94-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про організацію обліку дітей дошкільного віку (лист МОН України &#8470;1/9-263 від 07.05.2007 р.).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><span style="color: blue; line-height: 20.8px;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/12.doc" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про організацію короткотривалого перебування дітей у дошкільних навчальних закладах (лист МОН України &#8470;1/9-577 від 29.07.2011 р.).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/13.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Рекомендації щодо порядку використання державної символіки в навчальних закладах України, затверджені наказом Міністерства освіти і науки України  від 7 вересня 2000 р. &#8470;439.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/I/14.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Національна стратегія розвитку освіти в Україні на період до 2021 року.&nbsp;</span><span style="background-color: white; border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon0.rada.gov.ua/laws/show/344/2013" style="background-color: transparent; border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;">Щодо здійснення вчителем науково-дослідницької діяльності та пошукової роботи.&nbsp;Лист МОН &#8470; 1/9-586 від 11.11.14 року.&nbsp;<a href="http://ru.osvita.ua/legislation/Ser_osv/43886/" target="_blank">Джерело</a></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center"  style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 2% 0px 1% 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="border: 0px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">
                            <span style="font-family: georgia , times new roman , serif;">ІІ. Установчі документи</span></span></h4>
                    <div  style="background-color: rgba(255, 255, 255, 0.309804); margin-left:10%; border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%;margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <div style="color: #363636;">
                        </div>
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Положення про дошкільний навчальний заклад. затверджене постановою Кабінету Міністрів України від 12 березня 2003 р. &#8470;305.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/305-2003-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Положення про навчально-виховний комплекс &#171;загальноосвітній навчальний заклад &#8211; дошкільний навчальний заклад&#187;, затверджено постан</span><span style="line-height: 20.8px;">овою Кабінету Міністрів України від 12 березня 2003 р. &#8470;306.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/306-2003-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>П</span></a><a href="http://zakon2.rada.gov.ua/laws/show/306-2003-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>ереглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про затвердження примірного статуту дошкільного навчального закладу (наказ Міністерства освіти і науки від 24.04.2003 р. &#8470; 257).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/II/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про застосування Типових штатних нормативів дошкільних закладів (лист від 18.02.2011 &#8470;1/9-114).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/II/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Про режим роботи дошкільних навчальних закладів (лист МОН України &#8470;1/9-36 від 24.01.2007 р.).</span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Типові штатні нормативи дошкільних навчальних закладів (затверджені наказом Міністерства освіти і науки &#8470;1055 від 04.11.2010).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/II/06.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4  class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ІІІ. Атестація</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1% ; margin-left:10%;margin-right: 5%; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про проведення державної атестації дошкільних навчальних закладів (лист Міністерства освіти і науки України від 15.05.2012 р. &#8470;1/9-363).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/III/01.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Типове положення &#171;Про атестацію педагогічних працівників&#187;, затверджене наказом Міністерства освіти України від 06.10.2010 р. &#8470;930. {Із змінами, внесеними згідно з наказом Міністерства освіти і науки, молоді та спорту&nbsp;</span><a href="http://osvita.ua/legislation/Ser_osv/26746" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">&#8470; 1473</a><span style="line-height: 20.8px;">&nbsp;від 20.12.2011, наказом МОН&nbsp;</span><a href="http://osvita.ua/legislation/Ser_osv/37013/" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank" title="Про затвердження Змін до Типового положення про атестацію педагогічних працівників">&#8470; 1135</a><span style="line-height: 20.8px;">&nbsp;від 08.08.2013}.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/III/02.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="background-color: white; font-family: georgia , times new roman , serif; line-height: 18px;">Про затвердження кваліфікаційних характеристик професій (посад) педагогічних та науково-педагогічних працівників навчальних закладів (Наказ МОН &#8470; 665 від 01.06.13 року).&nbsp;&nbsp;</span><a href="http://osvita.ua/legislation/other/37302/" style="background-color: white; font-family: georgia, 'times new roman', serif; line-height: 18px;" target="_blank">Переглянути</a></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'" >
                    <h4 class="text-center"style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ІV. Діловодство</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px;margin-left:10%;margin-right: 5%;  margin-bottom: 1%; margin-top: 12px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;">Примірна інструкція з діловодства у дошкільних навчальних закладах,затверджена наказом МОНмолодьспорту України&#8470; 1059&nbsp;від 01.10.2012. <a href="https://docs.google.com/document/d/1WiF_qfnT7k69pRFvXHX75a6RaZh_olNXPHWnkGeOVP8/edit" target="_blank">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Інструкція &#171;Про порядок ведення книжок працівників&#187;, затверджена 29.07.93 &#8470;58.&nbsp;</span><span style="border: 0px; color: blue; font-family: georgia , times new roman , serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/IV/02.doc" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Про затвердження інструкції з діловодства за зверненням громадян в органах державної влади і місцевого самоврядування, об&#8217;єднаннях громадян, на підприємствах, в установах, організаціях незалежно від форм власності, в засобах масової інформації, постанова кабінету міністрів України від 14 квітня 1997 р. &#8470;348.</span><span style="color: #363636; font-family: georgia , times new roman , serif; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/348-97-%D0%BF" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">V. Кадрове забезпечення</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px;margin-left:10%;; margin-bottom: 12px; margin-top: 12px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Перелік посад педагогічних та науково-педагогічних працівників, затверджений постановою Кабінету Міністрів України від 14.06.2000 &#8470;963.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon2.rada.gov.ua/laws/show/963-2000-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про гарантії і компенсації для працівників, які направляються для підвищення кваліфікації&#8230;, затверджений постановою Кабінету Міністрів України від 28.06.1997 &#8470;695.&nbsp;</span><a href="http://zakon1.rada.gov.ua/laws/show/695-97-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Щодо посади помічника вихователя, лист МОН та ЦК профспілки &#8230; від 19.03.2009 &#8470;1/9-176, &#171;02-5/116&#187;.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/V/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">VІ. Медичне обслуговування</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-left:10%; margin-right: 5%;  margin-top: 1%; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;"><div class="MsoNormal">
                               <span style="line-height: 115%;"><span style="line-height: 20.8px; text-align: center;"><span style="line-height: 115%;">Санiтарний регламент для дошкiльних навчальних закладiв. &nbsp;</span>
                               </span>
                                  </span><span style="line-height: 115%;">Наказ Мiнiстерства охорони здоров&#8217;я України від&nbsp;</span><span style="line-height: 115%;">2</span><span style="line-height: 115%;">4 березня 2016 року &#8470; 234. <a href="https://docs.google.com/document/d/1Rf6dE7ph6RIlS0p3yNx5PjNUXzp-i1xxzmtDfGBJ8HM/edit" target="_blank"><span >Переглянути</span></a></span></div>
                                     </span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про вдосконалення організації медичного обслуговування дітей у дошкільному навчальному закладі (наказ Міністерства освіти і науки України від&nbsp;30.08.2005 &#8470; 432/496).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/VI/432.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок медичного обслуговування дітей у дошкільних навчальних закладах,затверджений Постановою Кабінету Міністрів України від 14.06.2002 &#8470;826.&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon2.rada.gov.ua/laws/show/826-2002-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;">Законодавчі підстави щодо зарахування дітей без щеплень. Лист_ЛПЗ/ <a href="https://docs.google.com/document/d/1bpgsP_SJ6GsgDB2CPWr6c37mi1ovxT9tPlDV42jJZuI/edit" target="_blank">Переглянути</a>/ Стаття/<a href="https://docs.google.com/document/d/1o4gC7Ugc3ymDQ1R8LKjDr1WiKuTAEoVU_bShSkjq3ek/edit" target="_blank">Переглянути</a></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center"style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">VІІ. Методичний кабінет</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Примірне положення про методичний кабінет закладу дошкільної освіти. Наказ Міністерства освіти і науки України від 16.04.2018 &#8470; 372.&nbsp;</span><a href="https://www.pedrada.com.ua/files/articles/2290/Polozhennia_Metodkabinet_ZDO_MON_2018_Pedrada.pdf" target="_blank">Джерело</a></span></li>
                            <li><span style="background-color: white; font-family: georgia , times new roman , serif; font-size: medium ; text-align: left;">Про розроблення програм для дошкільної освіти.&nbsp;</span><span style="background-color: white; font-family: georgia , times new roman , serif; text-align: left;">Лист МОНмолодьспорт &#8470; 1/9-152 від 28.02.13 року. <a href="http://ru.osvita.ua/legislation/doshkilna-osvita/34830/" target="_blank">Джерело</a></span></li>
                        </ul>
                    </div>
                </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">VІІІ. Обладнання</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left:10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про затвердження Примірного переліку ігрового та навчально-дидактичного обладнання для закладів дошкільної освіти (Лист Міністерства освіти і науки України від 19.12.2017 р. &#8470;1633). <a href="https://osvita.ua/doc/files/news/586/58626/Nakaz_MON_19122017_1633.pdf" target="_blank">Переглянути</a></span></span></li>
                        </ul>
                    </div>
                </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ІХ. Планування</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%;margin-left:10%;margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;"><span style="background-color: white;text-align: -webkit-center;">Про планування освітнього процесу в дошкільному навчальному закладі. Лист МОН України&nbsp;&nbsp;</span></span></span><span style="font-family: georgia , times new roman , serif;">N 1/9-434&nbsp;<span style="background-color: white; color: #252525; text-align: -webkit-center;">від</span>&nbsp;01.10.2002 року. <a href="http://consultant.parus.ua/?doc=08GFQD7546" target="_blank">Джерело</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Планування роботи в дошкільних навчальних закладах (лист Міністерства освіти і науки України від 03.07.2009 р. &#8470;1/9-455).</span><span style="line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/IX/01.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про організацію і самостійну діяльність дітей у дошкільному навчальному закладі (&#8470; 14/18-3082 від 26.07.2010).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/IX/02.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Лист Міністерства освіти і науки України від 27 серпня 2000 р. 1/9-352 (рекомендації щодо планування діяльності, ведення документації і звітності усіх планок психологічної служби системи освіти України).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/IX/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </ul>
                    </div>
                </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">Х. Психологічна служба</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left:10%;margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Положення про психологічну службу системи освіти України, затверджене наказом Міністерства освіти України від 3 травня 1999 р. &#8470;127.</span><span style="line-height: 20.8px;">&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/z0922-99" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Положення про психологічний кабінет дошкільних, загальноосвітніх та інших навчальних закладів системи загальної середньої освіти, затверджене наказом міністерства освіти і науки України  від 19 жовтня 2001 р. &#8470;691.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/X/02.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про атестацію практичних психологів і соціальної роботи (лист Міністерства освіти і науки України від 13 грудня 2001 р. &#8470;1/9-439).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/X/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про планування діяльності та ведення документації соціальних педагогів, соціальних педагогів по роботі з дітьми-інвалідами системи Міністерства освіти і науки України, наказ міністерства освіти і науки України від 28 грудня 2006 р. &#8470;864.</span><span style="line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/X/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;">Психологічний супровід готовності до навчання дітей дошкільного віку. Методичні рекомендації КУ "ММК ДО ВМР" від 21.03.2018&nbsp; &#8470; 108. <a href="https://docs.google.com/document/d/1lCjVsz5e6QdjOaSaajRE4_0GBTHHPohHrsIKtCRngoQ/edit#heading=h.gjdgxs" target="_blank">Переглянути</a>&nbsp;&nbsp;</span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХІ. Оплата праці</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 12px; margin-left: 10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Інструкція про порядок обчислення заробітної плати працівників освіти, затверджена наказом МОН України від 15.04.1993 &#8470;102.&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/z0056-93"><span></span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про встановлення надбавки педагогічним працівникам дошкільних.., затверджено постановою Кабінету Міністрів України від 23.03.2011 &#8470;373.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/373-2011-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про доплату за перевищення планової наповнюваності груп, лист МОН України від 26.11.2008 &#8470;1/9-764.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XI/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про внесення змін до Інструкції про порядок обчислення заробітної плати працівників освіти, наказом МОН України від 24.02.2005 &#8470;118.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/z0281-05" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок виплати надбавок за вислугу років педагогічним та науково-педагогічним працівникам навчальних закладів і установ освіти, затверджений постановою Кабінету міністрів України від 31.01.2001 &#8470;78.&nbsp;</span><a href="http://zakon1.rada.gov.ua/laws/show/78-2001-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про оплату праці працівників освіти і науки в умовах епідемії грипу, лист МОН України від 02.11.2009 &#8470;1/9-757; &#8470;02-8/437.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XI/06.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про оплату праці працівників на основі Єдиної тарифної сітки розрядів і коефіцієнтів з оплати праці працівників установ, закладів та організацій окремих галузей бюджетної сфери, постанова Кабінету Міністрів України від 30 серпня 2002 р. &#8470;1298.<span style="color: blue;">&nbsp;</span></span><a href="http://zakon4.rada.gov.ua/laws/show/1298-2002-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Схема тарифних розрядів посад керівних та педагогічних працівників дитячих дошкільних навчальних закладів усіх типів і найменувань (крім дитячих будинків), наказом МОН України від 26.09.2005 &#8470;557.&nbsp;</span><a href="http://zakon0.rada.gov.ua/laws/show/z1130-05" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a><span style="color: #363636; line-height: 20.8px;">&nbsp;</span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про внесення зміни до наказу Міністерства освіти і науки України від 26.09.2005 &#8470; 557.&nbsp;</span><span style="color: blue;"><a href="http://zakon0.rada.gov.ua/laws/show/z0714-13" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a><span style="line-height: 20.8px;">&nbsp;</span></span></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХІІ. Охорона праці. Безпека життєдіяльності у ЗДО</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%;margin-left:10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Інструкція з організації охорони життя і здоров&#8217;я дітей у дошкільних навчальних закладах (наказ МОН України від 28.10.2008 &#8470;985).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XII/02.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Наказ Міністерства охорони життя і здоров&#8217;я України від 23.07.2002 &#8470;280. Щодо організації проведення обов&#8217;язкових профілактичних медичних оглядів працівників окремих професій, виробництв і організацій, діяльність яких пов&#8217;язана з обслуговуванням населення і може привести до поширення інфекційних хвороб.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XII/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a><span style="color: #363636; line-height: 20.8px;">&nbsp;</span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">П</span><span style="line-height: 20.8px;">ро внесення змін до наказу Міністерства охорони здоров'я України від 23 липня 2002 року &#8470; 280.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XII/03a.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Лист Міністерства &#8470; 1/9-482 від 23.09.2014 "Щодо організації роботи з питань охорони праці та безпеки життєдіяльності у дошкільних навчальних закладах"&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XII/1_9-482_po_ohoroni_pratsi.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="font-family: georgia , times new roman , serif;">Про затвердження Положення про порядок проведення навчання і перевірки знань з питань охорони праці&nbsp; та безпеки життєдіяльності в закладах, установах, організаціях, підприємствах, що належать до сфери управління Міністерства освіти і науки України </span><span style="font-family: georgia , times new roman , serif;">(<span id="docs-internal-guid-1c5e7f47-428c-1444-fe07-5668503b18e9"><span style="background-color: transparent; font-variant-east-asian: normal; font-variant-numeric: normal; vertical-align: baseline; white-space: pre-wrap;">із змінами, внесеними згідно з Наказом Міністерства освіти і науки </span><span style="background-color: transparent;  vertical-align: baseline; white-space: pre-wrap;"><a href="http://zakon2.rada.gov.ua/laws/show/z1512-17/paran6#n6" style="text-decoration-line: none;">&#8470; 1514 від 22.11.2017</a>)</span></span></span><span style="font-family: georgia , times new roman , serif;">&nbsp;</span><a href="https://docs.google.com/document/d/1r72XC-R3SwfAr9RTW557mFkuZya28YJBR3GYVB9OGdI/edit" style="font-family: georgia, times new roman, serif;" target="_blank">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;">Правила пожежної безпеки для навчальних закладів та&nbsp;установ системи освіти України, затверджені наказом Міністерства освітиm і&nbsp;науки України від 15.08.2016 &#8470;&nbsp;974. <a href="http://zakon5.rada.gov.ua/laws/show/z1229-16" target="_blank">Джерело</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;">Положення про організацію роботи з охорони праці та безпеки життєдіяльності учасників освітнього процесу в установах і закладах освіти (наказ Міністерства освіти і науки України 26 грудня 2017 року N 1669). <a href="https://drive.google.com/drive/folders/0B-rCUgEgFG3Qa2Rkd3BoVS0zTHM" target="_blank">Переглянути</a></span></li>
                        </ul>
                    </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХІІІ. Робота з дітьми, які не відвідують ЗДО</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Інструктивно-методичний лист МОН України від 27.09.2010 &#8470;1/9-666 &#171;Про організацію роботи з дітьми 5-річного віку&#187;.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIII/01.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про систему роботи з дітьми, які не відвідують дошкільні навчальні заклади (лист МОН України &#8470;1/9-583 від 04.10.2007).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIII/02.pdf" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про організацію роботи з дітьми старшого дошкільного віку, які не відвідують дошкільні заклади (лист МОН &#8470; 1/9-510 від 18.12.2000 року).&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIII/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про затвердження Примірного положення про консультативний центр для батьків або осіб, які їх замінюють і дітей, які виховуються в умовах сім&#8217;ї  (Наказ Міністерства і науки, молоді та спорту України від 30.06.2011 &#8470;714).</span><span >&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIII/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </ul>
                    </div>
                </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХІV. Взаємодія з батьками</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%;margin-left: 10%;margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Лист Міністерства освіти і науки України від 11.10.2017 року &#8470;1/9-546 &#171;Методичні рекомендації щодо організації взаємодії закладів дошкільної освіти з батьками вихованців&#187;. <a href="https://docs.google.com/document/d/18N6AZCncQkXypvkLQ-nsAF7NIsj992t8S7Kx3ymNOIM/edit" target="_blank">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про затвердження встановлення плати для батьків за перебування дітей у державних і комунальних дошкільних та інтернат них навчальних закладах, наказ МОН України від 21.11.2002 р. &#8470;667.&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/z0953-02" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Про невідкладні питання діяльності дошкільних та інтернатних навчальних закладів, постанова Кабінету Міністрів України від 26.08.2002 &#8470;1243.</span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про організацію роботи з дітьми п&#8217;ятирічного віку (лист МОН України &#8470;1/9-666 від 27.09.2010 р.).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/1243-2002-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про здійснення соціально-педагогічного патронату (лист МОН України &#8470;1/9-811 від 17.12.2008 р.).</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIV/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Примірне положення про консультативний центр для батьків або осіб, які їх замінюють і дітей, які виховують в умовах сім&#8217;ї, затверджене наказом МОН&#8230; України 30.06.2011 &#8470;714.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XIV/05.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </ul>
                    </div>
                </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХV. Стимулювання праці</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%;margin-left: 10%; margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок надання щорічної грошової винагороди педагогічним працівникам навчальних закладів державної та комунальної форми власності за сумлінну працю, зразкове виконання службових обов&#8217;язків, затверджений постановою Кабінету Міністрів України від 05.06.2000 &#8470;898.&nbsp;</span><a href="http://zakon2.rada.gov.ua/laws/show/898-2000-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Положення про нагородження грудним знаком &#171;Відмінник освіти України&#187;, &#171;Софія Русова&#187; Міністерства освіти і науки України, наказ МОН України від 11.07.2005 &#8470;402.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/z0820-05" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </ul>
                    </div>
                    </div>
                        <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХVІ. Час відпочинку</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%;  margin-right: 5%;  outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <Ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Орієнтовний перелік посад працівників з ненормованим робочим днем системи міністерства освіти України, який може надаватись додаткова відпустка, затверджено 11.03.1998.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVI/01.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок надання щорічної основної відпустки &#8230;, затверджений постановою Кабінету Міністрів України від 14.04.1997 &#8470;346.&nbsp;</span><span style="color: blue; line-height: 20.8px;"><a href="http://zakon3.rada.gov.ua/laws/show/346-97-%D0%BF" style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про надання навчальної відпустки, лист Міністерства праці та соціальної політики України від 06.09.2005 &#8470;09-402</span><span style="color: #363636; line-height: 20.8px;">.&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVI/03.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Про право одиноких матерів на додаткову відпустку на дітей, лист Міністерства праці та соціальної політики України від 25.08.2005 &#8470;36-455.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVI/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                        </Ul>
                    </div>
                        </div>
                    </div>
                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 CLASS="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХVІІ. Фізичне виховання</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Інструктивно-методичні рекомендації&nbsp;<span style="text-align: center;">&#171;Організація фізкультурно-оздоровчої роботи у дошкільних навчальних закладах&#187;&nbsp;</span></span>(лист МОН України &#8470;1/9-456&nbsp;від 02.09.2016 р.). <a href="https://docs.google.com/document/d/1pVtZKbtaC-AfR35bM57zMJOQvZo5V-0zShoIvfZfL9M/edit" target="_blank">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Фізичний розвиток дітей в умовах дошкільного навчального закладу (лист МОН України &#8470;1/9-563 від 16.08.2010 р.).&nbsp;</span><span style="border: 0px; color: blue; font-family: georgia , times new roman , serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVII/02.doc" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Державні вимоги до системи фізичного виховання дітей, учнівської і студентської молоді, затверджені наказом Міністерства освіти України від 25 травня 1998 р. &#8470;188.</span><span style="color: #363636; font-family: georgia , times new roman , serif; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-family: georgia , times new roman , serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVII/03.doc" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Система організації фізкультурно-оздоровчої та спортивної роботи дошкільних, загальноосвітніх, професійно-технічних та позашкільних навчальних закладів, затверджена наказом Міністерства освіти і науки України від 21 липня 2003 р. &#8470;486.</span><span style="color: #363636; font-family: georgia , times new roman , serif; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-family: georgia , times new roman , serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVII/04.doc" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Положення про організацію фізичного виховання і масового спорту в дошкільних, загальноосвітніх, професійно-технічних та позашкільних навчальних закладів, затверджена наказом Міністерства освіти і науки України від 2 серпня 2005 р. &#8470;458.</span><span style="color: #363636; font-family: georgia , times new roman , serif; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-family: georgia , times new roman , serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://zakon4.rada.gov.ua/laws/show/z0909-05" style="border: 0px; font-family: georgia, times new roman, serif; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></li>
                        </ul>
                    </div>
                    </div>

                    <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                    <h4 class="text-center" style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; margin: 18px 0px; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <span style="font-family: georgia , times new roman , serif;">ХVІІІ. Харчування</span></h4>
                    <div style="background-color: rgba(255, 255, 255, 0.309804); border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1% ;margin-left: 10%; margin-right: 5%; outline: 0px; padding: 0px; text-align: justify; vertical-align: baseline;">
                        <ul>
                            <li>
                            <span style="border: 0px; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="font-family: georgia , times new roman , serif;">Про затвердження Змін до Інструкції з організації харчування дітей у дошкільних навчальних закладах</span><span style="font-family: monospace;"><span style="white-space: pre;">. </span></span></span><span style="font-family: georgia , times new roman , serif;">Наказ МОНмолодьспорту України, МОЗ України від&nbsp;</span><span style="border: 0px; font-family: georgia , times new roman , serif; margin: 0px; outline: 0px; padding: 0px; text-align: center; vertical-align: baseline;">26.02.2013</span><span style="font-family: georgia , times new roman , serif; text-align: center;">&nbsp;&#8470;&nbsp;</span><span style="border: 0px; font-family: georgia , times new roman , serif; margin: 0px; outline: 0px; padding: 0px; text-align: center; vertical-align: baseline;">202/165. <a href="http://zakon0.rada.gov.ua/laws/show/z0440-13" target="_blank">Переглянути</a></span>

                            </li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Закон про дитяче харчування від 14.09.2006 року &#8470;142-V.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/142-16" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Норми харчування у навчальних та оздоровчих закладах, затверджені постановою Кабінету Міністрів України від 22.11.2004 &#8470;1591.&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/1591-2004-%D0%BF" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Пам&#8217;ятка вивчення управлінської діяльності з питань організації харчування дітей у дошкільних навчальних закладах, лист МОН України &#8470;1/9-394 від 21.06.2007 р.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVIII/04.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span >Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Порядок організації харчування дітей у навчальних та оздоровчих закладах, затверджена наказом Міністерства освіти і науки України, Міністерства охорони здоров&#8217;я України 01.06.2005 р. &#8470;242/329.</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><a href="http://zakon4.rada.gov.ua/laws/show/z0661-05" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><span>Переглянути</span></a></span></li>
                            <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Про виконання норм харчування у дошкільних навчальних закладах, лист МОН України від 19.05.2008 &#8470;1/9-323.</span></li>
                            <li><span style="font-family: georgia , times new roman , serif;"><span style="line-height: 20.8px;">Щодо внесення змін до постанови&nbsp;Кабінету Міністрів України&nbsp;від 22 листопада 2004 р. &#8470; 1591</span><span style="color: #363636; line-height: 20.8px;">&nbsp;</span><span style="border: 0px; color: blue; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;"><a href="http://dyvokray.org.ua/images/docs/normatuvni/XVIII/%D0%B7%D0%BC%D1%96%D0%BD%D0%B8_%D0%B4%D0%BE_%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8_%D0%BF%D1%80%D0%BE_%D1%85%D0%B0%D1%80%D1%87%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B4%D1%96%D1%82%D0%B5%D0%B9_%D0%B2_%D0%94%D0%9D%D0%97.doc" style="border: 0px; font-style: inherit; font-weight: inherit; line-height: 20.8px; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">Переглянути</a></span></span></li>
                        </ul>
                        </div>
                        </div>
                          <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                            <h4 class="text-center" style="border: 0px; margin: 20px; margin-left: -5%; outline: 0px; padding: 0px; vertical-align: baseline;">
                                <span style="font-family: georgia , times new roman , serif;">ХІ</span><span style="font-family: georgia , times new roman , serif;">Х</span><span style="font-family: georgia , times new roman , serif;">. Організація освітнього процесу</span></h4>
                            <div style="border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%; outline: 0px; padding: 0px; vertical-align: baseline;">
                                <ul>
                                    <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Інструктивно-методичні рекомендації&nbsp;<span style="text-align: center;">&#171;<span id="docs-internal-guid-c718b111-f7cf-2240-3d36-4c0543285b4a">Щодо організації роботи з музичного виховання дітей у дошкільних навчальних закладах</span>&#187;&nbsp;</span></span><span style="font-family: georgia , times new roman , serif;">(лист МОН України &#8470;<span id="docs-internal-guid-c718b111-f7d0-2fdc-d5de-e759176d2dc9"><span style="background-color: transparent; font-family: times new roman; font-size: 16px; vertical-align: baseline; white-space: pre-wrap;">1/9-454</span></span>&nbsp;від 02.09.2016 р.). <a href="https://docs.google.com/document/d/1XIbuEbSy7dW0zljpqO1ujFgEjayyks9VDuPXHAhOM34/edit" target="_blank">Переглянути</a></span></li>
                                </ul>
                            </div>
                        </div></div>
                        <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                            <h4 class="text-center" style="border: 0px; margin: 20px; margin-left: -5%; outline: 0px; padding: 0px; vertical-align: baseline;">
                                <span style="font-family: georgia , times new roman , serif;">Х</span><span style="font-family: georgia , times new roman , serif;">Х</span><span style="font-family: georgia , times new roman , serif;">. Нова українська школа&nbsp;</span></h4>
                            <div style="border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%; outline: 0px; padding: 0px; vertical-align: baseline;">
                                <ul>
                                    <li><span style="font-family: georgia , times new roman , serif; line-height: 20.8px;">Методичні рекомендації щодо організації освітнього простору Нової української школи. Наказ МОН від 23.03.2018 р. &#8470; 283. <a href="http://nus.org.ua/wp-content/uploads/2018/03/Nakaz-283-vid-23.03.2018-1.pdf" target="_blank">Переглянути&nbsp;</a></span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Використання LEGO в початковій школі. Гра по-новому, навчання по-іншому. Методичний посібник. <a href="https://mon.gov.ua/storage/app/media/nova-ukrainska-shkola/LEGO/po-novomu-navchannya-po-inshomu.pdf" target="_blank">Переглянути&nbsp;</a></span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Використання LEGO в початковій школі.&nbsp;Шість цеглинок. Методичний посібник.&nbsp;<a href="https://mon.gov.ua/storage/app/media/nova-ukrainska-shkola/LEGO/tseglinok-kviten-2018-web.pdf" target="_blank">Переглянути</a></span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Інструктивно-методичні рекомендації щодо забезпечення наступності дошкільної та початкової освіти. Додаток до </span><span style="border: 0px; box-sizing: border-box; line-height: 1.2; list-style: none; margin: 0px; outline: none; padding: 0px;"><span style="font-family: georgia , times new roman , serif;">листа&nbsp; МОН України&nbsp;&#8470;1/9-249 від 19 квітня 2018 р. <a href="https://docs.google.com/document/d/1GdXKS65haztV_l--XA-DpUybm6dg4Zijz52G-JAejR0/edit" target="_blank">Переглянути</a></span></span></li>
                                    <li><span style="border: 0px; box-sizing: border-box;  font-family: georgia , times new roman , serif; line-height: 1.2; list-style: none; margin: 0px; outline: none; padding: 0px;">Методичні рекомендації щодо розвитку STEM-освіти в закладах загальної середньої та позашкільної освіти України у 2018/2019 навчальному році. Лист ДНУ &#171;Інститут
                                          модернізації змісту освіти&#187; від 19.07.2018 &#8470; 22.1/10-2573. <a href="https://drive.google.com/drive/folders/0B-rCUgEgFG3Qa2Rkd3BoVS0zTHM?ogsrc=32" target="_blank">Переглянути</a></span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Про затвердження методичних рекомендацій щодо адаптаційного періоду для учнів першого класу у Новій українській школі. Наказ МОН &#8470; 923 від 20.08.2018 року. <a href="http://ru.osvita.ua/legislation/Ser_osv/61778/" target="_blank">Джерело</a></span></li>
                                </ul>
                            </div>
                        </div>
                       <div class="hover" onmouseover="this.style.zoom=1.25; this.style.color='#007bff'" onmouseout="this.style.zoom=1; this.style.color='black'">
                                <h4 class="text-center" style="border: 0px; margin: 20px 0px; outline: 0px; padding: 0px; vertical-align: baseline;">
                                    <span style="font-family: georgia , times new roman , serif;">Х</span><span style="font-family: georgia , times new roman , serif;">ХІ</span><span style="font-family: georgia , times new roman , serif;">. Інклюзивна освіта</span></h4>
                                <div style="border: 0px; line-height: 20.8px; margin-bottom: 12px; margin-top: 1%; margin-left: 10%; margin-right: 5%; outline: 0px; padding: 0px; vertical-align: baseline;">
                                <ul>
                                    <li><span style="font-family: georgia , times new roman , serif;">Щодо організації інклюзивного навчання у закладах освіти у 2019/2020 навчальному році. Лист Міністерства освіти і науки України від 26.06.2019 &#8470;1/9-409. <a href="https://drive.google.com/drive/folders/1AOiP78yte-nnr4xYZavpWsZ4USRXR92K" target="_blank">Переглянути&nbsp;</a>&nbsp;</span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Про затвердження Типового переліку спеціальних засобів корекції психофізичного розвитку дітей з особливими освітніми потребами, які навчаються в інклюзивних та спеціальних групах закладів дошкільної освіти. Наказ Міністерства освіти і науки України&nbsp;від 01.04.2019 &#8470; 423. <a href="https://mon.gov.ua/ua/npa/pro-zatverdzhennya-tipovogo-pereliku-specialnih-zasobiv-korekciyi-psihofizichnogo-rozvitku-ditej-z-osoblivimi-osvitnimi-potrebami-yaki-navchayutsya-v-inklyuzivnih-ta-specialnih-klasah-zakladiv-zagalnoyi-serednoyi-osviti" target="_blank">Джерело</a></span></li>
                                    <li><span style="font-family: georgia , times new roman , serif;">Щодо організації діяльності інклюзивних груп у закладах дошкільної освіти. Лист Міністерства освіти і науки України від 13.11.2018 &#8470; 1/9-691. <a href="https://drive.google.com/drive/folders/0B-rCUgEgFG3Qa2Rkd3BoVS0zTHM" target="_blank">Переглянути&nbsp;</a></span></li>
                                </ul>
                                </div>
                        </div>
                    </div>
              



     @endsection
